
servlet:
  multipart:
    enabled: true
    ## ??? ? ??? ?? ?? ??
    location: ${user.home}/tmpfiles
    ## ??? ?? ??? (default: 1MB) ??? ?? ?? ??
    max-file-size: 2MB
    ## multipart/form-data ??? ?? ?? ?? (?? ?? ??? ? ? ?? default: 10MB)
    max-request-size: 20MB
    ## ??? ???? ???? ??? (default: 0B)
    ## ??? ??? fize-size-threshold ?? ?? ??? ??? location ??? ???? ?? ??? ??? ??
    ## file-size-threshold: 3MB
    ## resolve-lazily: true

